In [7]:
import os
import requests
import pandas as pd
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent / "scripts"))
from get_token import get_siar_token

In [18]:

import urllib

base_url = "https://servicio.mapa.gob.es/siarapi" 
user = "48644221A" 
password = "968796876aA" 

# URLs 
url_user = f"{base_url}/API/V1/Autenticacion/cifrarCadena?cadena={user}" 
url_password = f"{base_url}/API/V1/Autenticacion/cifrarCadena?cadena={password}" 

# Peticiones 
resp_user = requests.get(url_user) 
resp_pass = requests.get(url_password) 
user_enc = urllib.parse.quote(resp_user.text.strip()) 
pass_enc = urllib.parse.quote(resp_pass.text.strip()) 

url_token = f"{base_url}/API/V1/Autenticacion/obtenerToken?Usuario={user_enc}&Password={pass_enc}" 

token = requests.get(url_token) 

print(token.status_code) 
token = token.text

200

In [9]:
# base URL del servicio SIAR
BASE = "https://servicio.mapa.gob.es/siarapi"

## INFO DATOS

In [33]:
def get_info_df(token: str, tipo: str) -> pd.DataFrame:
    """
    Consulta Info/{tipo} en SIAR y devuelve un DataFrame con el campo 'datos'.
    tipo: CCAA, PROVINCIAS, ESTACIONES, ACCESOS, CODIGOSVALIDACION
    """
    tipo = tipo.upper().strip()

    r = requests.get(
        f"{BASE}/API/V1/Info/{tipo}",
        params={"token": token},
        timeout=30
    )
    r.raise_for_status()

    payload = r.json()

    # Si la API devuelve MensajeRespuesta (error lógico)
    if payload.get("MensajeRespuesta"):
        raise RuntimeError(payload["MensajeRespuesta"])

    datos = payload.get("datos")

    # Normalmente 'datos' es lista de dicts -> DataFrame directo
    if isinstance(datos, list):
        return pd.DataFrame(datos)

    # Por si en algún caso viene como dict (no habitual en Info, pero por robustez)
    if isinstance(datos, dict):
        return pd.DataFrame([datos])

    # Si viene vacío o inesperado, devuelve DF vacío
    return pd.DataFrame()

In [34]:
# CCAA
df_ccaa = get_info_df(token, "CCAA")
df_ccaa.head()

                     CCAA Codigo
0               Andalucía    AND
1                  Aragón    ARA
2  Principado de Asturias    AST
3          Islas Baleares    BAL
4         Castilla y León    CAL

In [23]:
# PROVINCIAS
df_provincias = get_info_df(token, "PROVINCIAS")
df_provincias.head()

          Provincia Codigo Codigo_CCAA
0             Álava     VI         PVA
1          Albacete     AB         CAM
2  Alicante/Alacant      A         VAL
3           Almería     AL         AND
4             Ávila     AV         CAL

In [15]:
# ESTACIONES
df_estaciones = get_info_df(token, "ESTACIONES")
df_estaciones

,Estacion,Codigo,Termino,Longitud,Latitud,Altitud,XUTM,YUTM,Huso,Fecha_Instalacion,Fecha_Baja,Red_Estacion
0,Tarazona,AB01,Tarazona de la Mancha,015512000W,391520000N,722,593160.00,4345720.00,30,1999-10-12T22:00:00,2025-06-16T22:00:00,Red de estaciones del Ministerio
1,Caudete,AB10,Caudete,005847000W,384404000N,563,675585.00,4289270.00,30,2000-12-10T23:00:00,None,Red de estaciones del Ministerio
2,Hellín,AB11,Hellín,013939625W,382752800N,498,616816.77,4258221.98,30,2025-06-03T22:00:00,None,Red de estaciones del Ministerio
3,Tarazona de la Mancha,AB12,Tarazona de la Mancha,015533101W,391410805N,721,592702.42,4343553.11,30,2025-06-16T22:00:00,None,Red de estaciones del Ministerio
4,Juanaco,AB02,Villarrobledo,023925000W,391558000N,705,529582.00,4346370.00,30,1999-10-12T22:00:00,None,Red de estaciones del Ministerio
...,...,...,...,...,...,...,...,...,...,...,...,...
628,Épila,Z05,Épila,011655000W,413459000N,327,643204.00,4604930.00,30,2003-09-17T22:00:00,None,Red de estaciones del Ministerio
629,Ejea de los Caballeros,Z06,Ejea de los Caballeros,011146000W,420551000N,316,649166.00,4662200.00,30,2003-09-22T22:00:00,None,Red de estaciones del Ministerio
630,Sádaba,Z07,Sádaba,011833000W,421602000N,432,639427.00,4680840.00,30,2003-09-22T22:00:00,None,Red de estaciones del Ministerio
631,Luna,Z08,Luna,005609000W,420544000N,406,670687.00,4662470.00,30,2003-09-23T22:00:00,None,Red de estaciones del Ministerio
632,Santa Engracia,Z09,Tauste,011949000W,415516000N,253,638436.00,4642380.00,30,2003-09-24T22:00:00,2006-11-30T23:00:00,Red de estaciones del Ministerio

In [21]:
# ACCESOS
df_accesos = get_info_df(token, "ACCESOS")
df_accesos.head()

,NumAccesosMinutoActual,MaxAccesosMinuto,NumAccesosDiaActual,MaxAccesosDia,RegistrosAcumuladosMinuto,MaxRegistrosMinuto,RegistrosAcumuladosDia,MaxRegistrosDia
0,3,100,17,1000,104,100,2394,10000

In [22]:
# CODIGOSVALIDACION
df_codigos_validadion = get_info_df(token, "CODIGOSVALIDACION")
df_codigos_validadion.head()

                                         Descripcion IdCodigoValidacion
0       Dato  incorporado sin ningún error (Nivel 1)                100
1  El dato ha sido editado manualmente por un usu...                101
2  El dato ha sido validado en Nivel 1 y es válid...                103
3  El dato ha sido editado (Nivel1)  y es válido ...                104
4  El dato ha sido insertado (Nivel1)  y es válid...                105

## SERVICIOS DE DATOS

In [48]:
def get_max_date_for_station(token: str, station_id: str) -> str:
    """
    Devuelve la fecha máxima disponible (YYYY-MM-DD) para una estación.
    Sustituye ENDPOINT según el manual.
    """
    # EJEMPLO: cambia esto por el endpoint real del PDF
    # endpoint = f"{BASE}/API/V1/Datos/FechasDisponibles/ESTACION"
    # params = {"token": token, "Id": station_id}
    # r = requests.get(endpoint, params=params, timeout=30)

    raise NotImplementedError("Rellena el endpoint real del manual.")

def get_daily_data_latest(token: str, station_ids: list[str], datos_calculados: bool = True):
    # 1) toma una estación “referencia” para sacar max date
    max_date = get_max_date_for_station(token, station_ids[0])

    params = {
        "token": token,
        "Id": station_ids,
        "FechaInicial": max_date,
        "FechaFinal": max_date,
        "DatosCalculados": "true" if datos_calculados else "false",
    }

    r = requests.get(f"{BASE}/API/V1/Datos/Diarios/ESTACION", params=params, timeout=60)
    r.raise_for_status()
    return r.json()

In [50]:
r.text

'{"datos":[{"Fecha":"2025-11-01T00:00:00","Estacion":"HU01","TempMedia":15.090,"TempMax":22.260,"HorMinTempMax":1300,"TempMin":8.690,"HorMinTempMin":650,"HumedadMedia":69.390,"HumedadMax":100.000,"HorMinHumMax":720,"humedadMin":42.760,"HorMinHumMin":1310,"VelViento":0.873,"DirViento":347.500,"VelVientoMax":5.772,"HorMinVelMax":1235,"DirVientoVelMax":292.400,"Radiacion":11.150,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.524012,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-02T00:00:00","Estacion":"HU01","TempMedia":14.140,"TempMax":18.710,"HorMinTempMax":1210,"TempMin":9.950,"HorMinTempMin":2340,"HumedadMedia":60.800,"HumedadMax":83.100,"HorMinHumMax":650,"humedadMin":37.690,"HorMinHumMin":1340,"VelViento":3.894,"DirViento":280.200,"VelVientoMax":10.790,"HorMinVelMax":1502,"DirVientoVelMax":272.900,"Radiacion":11.080,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":2.926253,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-03T00:00:00","Estacion":"HU01","TempMedia":11.580,"TempMax":19.680,"HorMinTempMax":1350,"TempMin":6.128,"HorMinTempMin":630,"HumedadMedia":65.140,"HumedadMax":81.900,"HorMinHumMax":650,"humedadMin":40.120,"HorMinHumMin":1340,"VelViento":1.435,"DirViento":300.800,"VelVientoMax":6.703,"HorMinVelMax":200,"DirVientoVelMax":277.900,"Radiacion":13.080,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.833271,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-04T00:00:00","Estacion":"HU01","TempMedia":11.330,"TempMax":19.030,"HorMinTempMax":1530,"TempMin":4.805,"HorMinTempMin":520,"HumedadMedia":76.100,"HumedadMax":100.000,"HorMinHumMax":2010,"humedadMin":54.740,"HorMinHumMin":1400,"VelViento":1.468,"DirViento":51.950,"VelVientoMax":4.243,"HorMinVelMax":1302,"DirVientoVelMax":93.800,"Radiacion":11.950,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.481378,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-05T00:00:00","Estacion":"HU01","TempMedia":14.200,"TempMax":20.540,"HorMinTempMax":1340,"TempMin":8.760,"HorMinTempMin":50,"HumedadMedia":82.600,"HumedadMax":100.000,"HorMinHumMax":620,"humedadMin":59.750,"HorMinHumMin":1320,"VelViento":2.824,"DirViento":78.100,"VelVientoMax":7.580,"HorMinVelMax":1946,"DirVientoVelMax":111.400,"Radiacion":10.030,"Precipitacion":1.960,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.8314,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-06T00:00:00","Estacion":"HU01","TempMedia":12.810,"TempMax":16.330,"HorMinTempMax":1210,"TempMin":9.880,"HorMinTempMin":2030,"HumedadMedia":76.400,"HumedadMax":100.000,"HorMinHumMax":120,"humedadMin":56.200,"HorMinHumMin":1210,"VelViento":3.484,"DirViento":271.400,"VelVientoMax":10.780,"HorMinVelMax":1133,"DirVientoVelMax":259.600,"Radiacion":8.690,"Precipitacion":23.910,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.720026,"PePMon":14.737924,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-07T00:00:00","Estacion":"HU01","TempMedia":11.640,"TempMax":17.320,"HorMinTempMax":1510,"TempMin":7.050,"HorMinTempMin":430,"HumedadMedia":68.130,"HumedadMax":80.600,"HorMinHumMax":2350,"humedadMin":53.880,"HorMinHumMin":1330,"VelViento":2.088,"DirViento":273.600,"VelVientoMax":6.850,"HorMinVelMax":1114,"DirVientoVelMax":270.500,"Radiacion":10.350,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.703423,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-08T00:00:00","Estacion":"HU01","TempMedia":11.740,"TempMax":16.790,"HorMinTempMax":1400,"TempMin":8.360,"HorMinTempMin":2350,"HumedadMedia":75.200,"HumedadMax":100.000,"HorMinHumMax":120,"humedadMin":55.600,"HorMinHumMin":1340,"VelViento":4.322,"DirViento":279.500,"VelVientoMax":9.240,"HorMinVelMax":1556,"DirVientoVelMax":273.500,"Radiacion":10.170,"Precipitacion":2.352,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.940688,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-09T00:00:00","Estacion":"HU01","TempMedia":9.740,"TempMax":17.450,"HorMinTempMax":1450,"TempMin":4.209,"HorMinTempMin":2230,"HumedadMedia":70.900,"HumedadMax":84.600,"HorMinHumMax":700,"humedadMin":49.650,"HorMinHumMin":1450,"VelViento":2.171,"DirViento":283.400,"VelVientoMax":6.497,"HorMinVelMax":16,"DirVientoVelMax":272.800,"Radiacion":11.980,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.762629,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-10T00:00:00","Estacion":"HU01","TempMedia":9.880,"TempMax":17.980,"HorMinTempMax":1450,"TempMin":1.774,"HorMinTempMin":650,"HumedadMedia":67.620,"HumedadMax":93.500,"HorMinHumMax":710,"humedadMin":40.790,"HorMinHumMin":1530,"VelViento":1.347,"DirViento":291.100,"VelVientoMax":5.762,"HorMinVelMax":1142,"DirVientoVelMax":304.700,"Radiacion":11.360,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.454306,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-11T00:00:00","Estacion":"HU01","TempMedia":9.860,"TempMax":17.770,"HorMinTempMax":1330,"TempMin":3.812,"HorMinTempMin":240,"HumedadMedia":76.200,"HumedadMax":100.000,"HorMinHumMax":2220,"humedadMin":56.310,"HorMinHumMin":1330,"VelViento":1.220,"DirViento":43.840,"VelVientoMax":3.900,"HorMinVelMax":1444,"DirVientoVelMax":86.300,"Radiacion":11.470,"Precipitacion":0.196,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.179239,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-12T00:00:00","Estacion":"HU01","TempMedia":12.590,"TempMax":19.950,"HorMinTempMax":1350,"TempMin":5.930,"HorMinTempMin":240,"HumedadMedia":81.000,"HumedadMax":100.000,"HorMinHumMax":840,"humedadMin":57.970,"HorMinHumMin":1350,"VelViento":2.651,"DirViento":61.060,"VelVientoMax":8.180,"HorMinVelMax":1228,"DirVientoVelMax":83.200,"Radiacion":10.440,"Precipitacion":0.196,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.708287,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-13T00:00:00","Estacion":"HU01","TempMedia":15.680,"TempMax":19.370,"HorMinTempMax":1340,"TempMin":11.940,"HorMinTempMin":310,"HumedadMedia":71.100,"HumedadMax":80.600,"HorMinHumMax":630,"humedadMin":62.020,"HorMinHumMin":1340,"VelViento":3.926,"DirViento":83.100,"VelVientoMax":9.080,"HorMinVelMax":1405,"DirVientoVelMax":109.400,"Radiacion":6.971,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":2.126841,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-14T00:00:00","Estacion":"HU01","TempMedia":15.350,"TempMax":19.240,"HorMinTempMax":1440,"TempMin":9.880,"HorMinTempMin":2030,"HumedadMedia":72.700,"HumedadMax":100.000,"HorMinHumMax":2030,"humedadMin":61.230,"HorMinHumMin":1240,"VelViento":1.602,"DirViento":87.000,"VelVientoMax":6.615,"HorMinVelMax":322,"DirVientoVelMax":81.300,"Radiacion":3.270,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.163905,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-15T00:00:00","Estacion":"HU01","TempMedia":12.320,"TempMax":18.180,"HorMinTempMax":1010,"TempMin":6.788,"HorMinTempMin":610,"HumedadMedia":68.520,"HumedadMax":85.400,"HorMinHumMax":2320,"humedadMin":40.000,"HorMinHumMin":1220,"VelViento":1.469,"DirViento":104.500,"VelVientoMax":6.497,"HorMinVelMax":2346,"DirVientoVelMax":273.900,"Radiacion":5.922,"Precipitacion":1.960,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.530513,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-16T00:00:00","Estacion":"HU01","TempMedia":11.620,"TempMax":18.250,"HorMinTempMax":1350,"TempMin":6.576,"HorMinTempMin":1920,"HumedadMedia":71.600,"HumedadMax":100.000,"HorMinHumMax":130,"humedadMin":49.250,"HorMinHumMin":1510,"VelViento":1.439,"DirViento":275.500,"VelVientoMax":7.250,"HorMinVelMax":1306,"DirVientoVelMax":268.900,"Radiacion":9.920,"Precipitacion":0.196,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.285351,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-17T00:00:00","Estacion":"HU01","TempMedia":10.870,"TempMax":16.860,"HorMinTempMax":1440,"TempMin":5.797,"HorMinTempMin":110,"HumedadMedia":70.000,"HumedadMax":83.700,"HorMinHumMax":700,"humedadMin":56.660,"HorMinHumMin":1510,"VelViento":1.994,"DirViento":282.700,"VelVientoMax":6.801,"HorMinVelMax":1248,"DirVientoVelMax":286.600,"Radiacion":10.680,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.412264,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-18T00:00:00","Estacion":"HU01","TempMedia":6.870,"TempMax":13.040,"HorMinTempMax":1330,"TempMin":1.575,"HorMinTempMin":2120,"HumedadMedia":62.950,"HumedadMax":80.300,"HorMinHumMax":330,"humedadMin":38.420,"HorMinHumMin":1520,"VelViento":2.971,"DirViento":280.700,"VelVientoMax":7.030,"HorMinVelMax":1127,"DirVientoVelMax":265.500,"Radiacion":11.190,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.853464,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-19T00:00:00","Estacion":"HU01","TempMedia":6.146,"TempMax":11.650,"HorMinTempMax":1420,"TempMin":0.516,"HorMinTempMin":630,"HumedadMedia":64.580,"HumedadMax":75.900,"HorMinHumMax":630,"humedadMin":45.110,"HorMinHumMin":1240,"VelViento":4.259,"DirViento":270.900,"VelVientoMax":10.570,"HorMinVelMax":1542,"DirVientoVelMax":301.700,"Radiacion":10.460,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.975081,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-20T00:00:00","Estacion":"HU01","TempMedia":6.950,"TempMax":10.860,"HorMinTempMax":1240,"TempMin":3.685,"HorMinTempMin":2350,"HumedadMedia":62.760,"HumedadMax":73.100,"HorMinHumMax":2240,"humedadMin":45.630,"HorMinHumMin":1320,"VelViento":6.789,"DirViento":282.700,"VelVientoMax":13.730,"HorMinVelMax":1019,"DirVientoVelMax":276.000,"Radiacion":10.420,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":2.438712,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-21T00:00:00","Estacion":"HU01","TempMedia":4.057,"TempMax":8.680,"HorMinTempMax":1300,"TempMin":-0.477,"HorMinTempMin":640,"HumedadMedia":55.780,"HumedadMax":77.400,"HorMinHumMax":640,"humedadMin":26.720,"HorMinHumMin":1300,"VelViento":5.836,"DirViento":287.800,"VelVientoMax":11.430,"HorMinVelMax":32,"DirVientoVelMax":288.800,"Radiacion":11.020,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":2.427317,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-22T00:00:00","Estacion":"HU01","TempMedia":4.713,"TempMax":10.660,"HorMinTempMax":1320,"TempMin":0.516,"HorMinTempMin":2320,"HumedadMedia":60.520,"HumedadMax":76.800,"HorMinHumMax":620,"humedadMin":35.980,"HorMinHumMin":1420,"VelViento":4.102,"DirViento":275.600,"VelVientoMax":8.790,"HorMinVelMax":1253,"DirVientoVelMax":254.800,"Radiacion":10.840,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":2.055678,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-23T00:00:00","Estacion":"HU01","TempMedia":9.550,"TempMax":14.760,"HorMinTempMax":1420,"TempMin":2.171,"HorMinTempMin":0,"HumedadMedia":58.670,"HumedadMax":70.700,"HorMinHumMax":2350,"humedadMin":46.030,"HorMinHumMin":1240,"VelViento":3.747,"DirViento":266.500,"VelVientoMax":10.090,"HorMinVelMax":1031,"DirVientoVelMax":283.600,"Radiacion":9.300,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":2.084053,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-24T00:00:00","Estacion":"HU01","TempMedia":11.440,"TempMax":17.390,"HorMinTempMax":1200,"TempMin":6.194,"HorMinTempMin":130,"HumedadMedia":67.460,"HumedadMax":92.300,"HorMinHumMax":1930,"humedadMin":46.480,"HorMinHumMin":1130,"VelViento":3.728,"DirViento":273.600,"VelVientoMax":11.430,"HorMinVelMax":1136,"DirVientoVelMax":265.300,"Radiacion":7.010,"Precipitacion":0.784,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":2.101863,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-25T00:00:00","Estacion":"HU01","TempMedia":7.850,"TempMax":12.710,"HorMinTempMax":1230,"TempMin":4.672,"HorMinTempMin":2340,"HumedadMedia":65.100,"HumedadMax":73.700,"HorMinHumMax":720,"humedadMin":50.070,"HorMinHumMin":1450,"VelViento":6.543,"DirViento":285.700,"VelVientoMax":15.080,"HorMinVelMax":1003,"DirVientoVelMax":256.100,"Radiacion":10.120,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":2.432035,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-26T00:00:00","Estacion":"HU01","TempMedia":5.978,"TempMax":12.120,"HorMinTempMax":1350,"TempMin":1.443,"HorMinTempMin":2340,"HumedadMedia":59.180,"HumedadMax":78.500,"HorMinHumMax":130,"humedadMin":29.430,"HorMinHumMin":1430,"VelViento":4.667,"DirViento":285.600,"VelVientoMax":9.920,"HorMinVelMax":1117,"DirVientoVelMax":277.700,"Radiacion":10.540,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":2.467472,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-27T00:00:00","Estacion":"HU01","TempMedia":5.416,"TempMax":14.080,"HorMinTempMax":1410,"TempMin":-1.126,"HorMinTempMin":230,"HumedadMedia":57.720,"HumedadMax":86.500,"HorMinHumMax":300,"humedadMin":23.340,"HorMinHumMin":1430,"VelViento":2.107,"DirViento":287.000,"VelVientoMax":5.802,"HorMinVelMax":440,"DirVientoVelMax":269.100,"Radiacion":10.350,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.72777,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-28T00:00:00","Estacion":"HU01","TempMedia":5.072,"TempMax":13.950,"HorMinTempMax":1400,"TempMin":-2.318,"HorMinTempMin":700,"HumedadMedia":68.820,"HumedadMax":81.300,"HorMinHumMax":710,"humedadMin":51.640,"HorMinHumMin":1400,"VelViento":0.853,"DirViento":298.000,"VelVientoMax":5.478,"HorMinVelMax":1435,"DirVientoVelMax":267.600,"Radiacion":9.150,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":0.7445977,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-29T00:00:00","Estacion":"HU01","TempMedia":4.788,"TempMax":14.350,"HorMinTempMax":1500,"TempMin":-1.391,"HorMinTempMin":720,"HumedadMedia":79.800,"HumedadMax":100.000,"HorMinHumMax":920,"humedadMin":46.550,"HorMinHumMin":1410,"VelViento":0.569,"DirViento":31.500,"VelVientoMax":3.440,"HorMinVelMax":1153,"DirVientoVelMax":295.400,"Radiacion":8.710,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":0.60184,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-11-30T00:00:00","Estacion":"HU01","TempMedia":5.743,"TempMax":12.180,"HorMinTempMax":1220,"TempMin":0.847,"HorMinTempMin":50,"HumedadMedia":80.600,"HumedadMax":100.000,"HorMinHumMax":740,"humedadMin":60.580,"HorMinHumMin":1220,"VelViento":1.639,"DirViento":315.400,"VelVientoMax":6.978,"HorMinVelMax":727,"DirVientoVelMax":271.400,"Radiacion":5.849,"Precipitacion":0.196,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":0.8492226,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-12-01T00:00:00","Estacion":"HU01","TempMedia":4.010,"TempMax":13.290,"HorMinTempMax":1430,"TempMin":-3.311,"HorMinTempMin":520,"HumedadMedia":80.300,"HumedadMax":100.000,"HorMinHumMax":850,"humedadMin":43.240,"HorMinHumMin":1430,"VelViento":0.728,"DirViento":358.800,"VelVientoMax":4.332,"HorMinVelMax":1251,"DirVientoVelMax":248.700,"Radiacion":9.500,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":0.6385776,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-12-02T00:00:00","Estacion":"HU01","TempMedia":4.470,"TempMax":12.510,"HorMinTempMax":1130,"TempMin":-1.524,"HorMinTempMin":610,"HumedadMedia":79.600,"HumedadMax":100.000,"HorMinHumMax":530,"humedadMin":50.860,"HorMinHumMin":1130,"VelViento":1.685,"DirViento":295.500,"VelVientoMax":7.660,"HorMinVelMax":1209,"DirVientoVelMax":250.000,"Radiacion":5.815,"Precipitacion":0.196,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.01314,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-12-03T00:00:00","Estacion":"HU01","TempMedia":6.069,"TempMax":12.770,"HorMinTempMax":1250,"TempMin":-0.146,"HorMinTempMin":550,"HumedadMedia":68.550,"HumedadMax":100.000,"HorMinHumMax":710,"humedadMin":43.840,"HorMinHumMin":1350,"VelViento":4.044,"DirViento":278.900,"VelVientoMax":9.870,"HorMinVelMax":1504,"DirVientoVelMax":265.800,"Radiacion":9.360,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.69973,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-12-04T00:00:00","Estacion":"HU01","TempMedia":6.805,"TempMax":11.410,"HorMinTempMax":1240,"TempMin":2.428,"HorMinTempMin":310,"HumedadMedia":73.600,"HumedadMax":91.900,"HorMinHumMax":1900,"humedadMin":60.490,"HorMinHumMin":10,"VelViento":2.454,"DirViento":266.600,"VelVientoMax":8.300,"HorMinVelMax":1147,"DirVientoVelMax":285.900,"Radiacion":4.959,"Precipitacion":0.196,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.053562,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-12-05T00:00:00","Estacion":"HU01","TempMedia":8.600,"TempMax":13.770,"HorMinTempMax":1330,"TempMin":4.077,"HorMinTempMin":2350,"HumedadMedia":71.500,"HumedadMax":94.000,"HorMinHumMax":430,"humedadMin":53.970,"HorMinHumMin":1440,"VelViento":4.153,"DirViento":274.700,"VelVientoMax":10.840,"HorMinVelMax":1214,"DirVientoVelMax":284.700,"Radiacion":8.830,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.571618,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-12-06T00:00:00","Estacion":"HU01","TempMedia":10.780,"TempMax":19.500,"HorMinTempMax":1340,"TempMin":2.696,"HorMinTempMin":120,"HumedadMedia":74.100,"HumedadMax":99.800,"HorMinHumMax":810,"humedadMin":52.630,"HorMinHumMin":1340,"VelViento":1.883,"DirViento":292.100,"VelVientoMax":9.340,"HorMinVelMax":1158,"DirVientoVelMax":264.900,"Radiacion":8.250,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.301336,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-12-07T00:00:00","Estacion":"HU01","TempMedia":13.130,"TempMax":18.640,"HorMinTempMax":1330,"TempMin":7.190,"HorMinTempMin":2330,"HumedadMedia":66.540,"HumedadMax":78.500,"HorMinHumMax":740,"humedadMin":47.930,"HorMinHumMin":1500,"VelViento":2.520,"DirViento":274.100,"VelVientoMax":7.410,"HorMinVelMax":1315,"DirVientoVelMax":265.100,"Radiacion":8.250,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":1.740487,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-12-08T00:00:00","Estacion":"HU01","TempMedia":7.890,"TempMax":16.380,"HorMinTempMax":1340,"TempMin":0.649,"HorMinTempMin":710,"HumedadMedia":76.100,"HumedadMax":100.000,"HorMinHumMax":720,"humedadMin":55.780,"HorMinHumMin":1340,"VelViento":0.647,"DirViento":36.960,"VelVientoMax":2.803,"HorMinVelMax":1504,"DirVientoVelMax":134.900,"Radiacion":9.140,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":0.5579968,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-12-09T00:00:00","Estacion":"HU01","TempMedia":6.644,"TempMax":14.550,"HorMinTempMax":1430,"TempMin":-0.278,"HorMinTempMin":710,"HumedadMedia":86.100,"HumedadMax":100.000,"HorMinHumMax":40,"humedadMin":59.570,"HorMinHumMin":1440,"VelViento":0.529,"DirViento":55.670,"VelVientoMax":3.136,"HorMinVelMax":1312,"DirVientoVelMax":84.600,"Radiacion":7.420,"Precipitacion":0.196,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":0.4910162,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-12-10T00:00:00","Estacion":"HU01","TempMedia":9.460,"TempMax":16.990,"HorMinTempMax":1150,"TempMin":4.805,"HorMinTempMin":230,"HumedadMedia":77.200,"HumedadMax":98.500,"HorMinHumMax":2350,"humedadMin":51.830,"HorMinHumMin":1150,"VelViento":1.282,"DirViento":306.300,"VelVientoMax":6.566,"HorMinVelMax":1343,"DirVientoVelMax":294.400,"Radiacion":7.120,"Precipitacion":0.000,"TempSuelo1":null,"TempSuelo2":null,"EtPMon":0.9517994,"PePMon":0.0,"CodTempSuelo1":null,"CodTempSuelo2":null},{"Fecha":"2025-12-11T00:00:00","Estaci